Repository f13babylon/f13babylon, pull requests merged in 2023-11, with the labels that each got.

#159 Removes Observer Blindening
  code/_onclick/hud/ghost.dm
  code/modules/mob/dead/observer/observer.dm
  modular_citadel/code/modules/client/client_procs.dm
Labels: do not merge

#155 bleed effect expansion (bleed added to ripper + other weapons)
  code/__DEFINES/status_effects.dm
  code/datums/status_effects/debuffs.dm
  code/modules/fallout/weapons/melee/powerfist.dm
  code/modules/fallout/weapons/melee/twohanded.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm
  code/modules/projectiles/projectile/reusable/arrow.dm
  icons/effects/bleed.dmi
Labels: do not merge, testmerged

#182 Ports CB's Throwing Casings Code
  code/__DEFINES/combat.dm
  code/__HELPERS/unsorted.dm
  code/modules/projectiles/ammunition/_ammunition.dm
  code/modules/projectiles/guns/ballistic.dm
Labels: testmerged

#166 no mans land; kebob changes
  _maps/map_files/Pahrump-Sunset/Dungeons.dmm
Labels: testmerged

#177 TGMC Particle Effects
  code/__DEFINES/generators.dm
  code/__DEFINES/particles.dm
  code/datums/elements/debris.dm
  code/game/atoms.dm
  code/game/mecha/equipment/tools/mining_tools.dm
  code/game/objects/effects/particle_holder.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/objs.dm
  code/game/objects/structures/crates_lockers/closets/gimmick.dm
  code/game/objects/structures/crates_lockers/crates/large.dm
  code/game/objects/structures/crates_lockers/crates/secure.dm
  code/game/objects/structures/crates_lockers/crates/wooden.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/window.dm
  code/game/turfs/closed.dm
  code/game/turfs/simulated/minerals.dm
  code/game/turfs/simulated/wall/mineral_walls.dm
  code/game/turfs/simulated/wall/reinf_walls.dm
  code/modules/fallout/obj/structures/barrel.dm
  code/modules/fallout/obj/structures/closets.dm
  code/modules/fallout/obj/structures/crates.dm
  code/modules/fallout/obj/structures/fridge.dm
  code/modules/fallout/obj/structures/simple_door.dm
  code/modules/fallout/obj/structures/vault_door.dm
  code/modules/fallout/obj/structures/wrecks.dm
  code/modules/fallout/turf/walls.dm
  code/modules/projectiles/projectile.dm
  fortune13.dme
  icons/effects/particles/generic_particles.dmi
Labels: testmerged

#195 Adds Beaker Shot Chance
  code/game/objects/items/grenades/grenade.dm
  code/modules/reagents/reagent_containers/glass.dm
Labels: Test Merge Candidate

#214 Human + Anthro Ghouls and Super Mutants
  code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
  code/modules/mob/living/simple_animal/hostile/f13/supermutant.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/behemoth.dm
  icons/fallout/mobs/behemoth.dmi
  icons/fallout/mobs/humans/ghouls.dmi
  icons/fallout/mobs/supermutant.dmi
  icons/fallout/mobs/supermutant_dead.dmi
Labels: Test Merge Candidate

#179 Great Oak Mountain Retreat, the final BoS rebase to end them all.
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Labels: Test Merge Candidate

#120 Repaths Powerfist
  code/_globalvars/lists/maintenance_loot.dm
  code/modules/fallout/f13lootdrop.dm
  code/modules/fallout/themed_loot_tables.dm
  code/modules/fallout/weapons/melee/powerfist.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/enclave.dm
  code/modules/jobs/job_types/legion.dm
Labels: Test Merge Candidate

#219 removes desert rose folder
  desertrose/icons/chat/chat.dmi
  desertrose/icons/chat/reward.dmi
  desertrose/icons/decals/decal_new.dmi
  desertrose/icons/mobs/aibots.dmi
  desertrose/icons/mobs/feet.dmi
  desertrose/icons/mobs/gloves.dmi
  desertrose/icons/mobs/head.dmi
  desertrose/icons/mobs/mimic.dmi
  desertrose/icons/mobs/rewards.dmi
  desertrose/icons/mobs/suit.dmi
  desertrose/icons/mobs/werewolf.dmi
  desertrose/icons/obj/bluespace_thread.dmi
  desertrose/icons/obj/clothing/gloves.dmi
  desertrose/icons/obj/clothing/head.dmi
  desertrose/icons/obj/clothing/rewards.dmi
  desertrose/icons/obj/clothing/shoes.dmi
  desertrose/icons/obj/leash.dmi
  desertrose/icons/obj/medical.dmi
  desertrose/icons/obj/plushes.dmi
  desertrose/icons/obj/pregnancytest.dmi
  desertrose/icons/obj/rope.dmi
  desertrose/modules/mob/carbon/human/life.dm
  desertrose/obj/fluff.dm
  desertrose/obj/pregnancytester.dm
Labels: Test Merge Candidate

#220 Fixes Broken Hairstyle + Some Cleaning
  code/modules/mob/dead/new_player/sprite_accessories/hair_face.dm
  code/modules/mob/dead/new_player/sprite_accessories/hair_head.dm
  code/modules/surgery/organs/eyes.dm
  icons/mob/hair.dmi
  icons/mob/human_face.dmi
Labels: Test Merge Candidate

#246 Explosive Collar Tweaks
  code/modules/fallout/obj/slavecollar.dm
  icons/mob/clothing/neck.dmi
  icons/obj/clothing/neck.dmi
Labels: Test Merge Candidate

#172 medmesh/medsuture changes
  code/game/objects/items/stacks/medical.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
Labels: do not merge
